name: Publish
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  uv-test:
    name: python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Setup Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build
        run: uv build

      - name: Audit manylinux
        run: |
          uv run auditwheel --manylinux 2_17 dist/*whl --exclude libscipy_openblas64_.so
          uv run twine upload wheelhouse/*manylinux* -p ${{ secrets.PYPI_TOKEN }}
